Algoritmo "senha"


Var

     senha, senhaGravada : inteiro

Inicio

     escreva("Digite uma senha para gravar: ")
     leia(senhaGravada)
     escreval("Senha salva com sucesso!")

      escreval("Digite a senha de acesso: ")
     leia(senha)


        enquanto senha <> senhaGravada faca
           escreva("Senha Invalida! Tente novamente: ")
           leia(senha)
        fimenquanto
        escreva("Acesso permitido!")

Fimalgoritmo
// Natan Mollica
